extends: rig_as_built.yaml
name: rgb2_thermal1_as_built_optimised
cameras:
- name: rgb_cam1
  pose:
    position:
    - -0.040699
    - -2.7e-05
    - 0.276
    azimuth_deg: 0.0379
    elevation_deg: -80.0
    roll_deg: -0.0
- name: rgb_cam2
  pose:
    position:
    - 0.010563
    - 0.001949
    - 0.276
    azimuth_deg: -169.5461
    elevation_deg: -80.0
    roll_deg: -0.0
- name: thermal
  pose:
    position:
    - 0.0
    - 0.0
    - 0.285
    azimuth_deg: 0.0
    elevation_deg: -90.0
    roll_deg: -90.0